package env

const (
	STG_SDK_API_HOST = "STG_SDK_API_HOST"
	STG_SDK_API_UN = "STG_SDK_API_UN"
	STG_SDK_API_PW = "STG_SDK_API_PW"
	STG_WEATHER_CONFIG_PATH = "STG_WEATHER_CONFIG_PATH"
	STG_WEATHER_EVENT_HUB_CONN = "STG_WEATHER_EVENT_HUB_CONN"
)
