
name: build

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string

jobs:
  dev-build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23' # The Go version to download (if necessary) and use.
      - run: go version
      - name: vet
        run: go vet -v ./...
      - name: test
        run: go test ./...
      - name: build
        run: go build ./cmd/${{ inputs.projectName }}
      - uses: actions/upload-artifact@v4
        with:
          name: executables
          path: ${{ inputs.projectName }}
