
name: dev
on:
  push:
    branches:
      - dev

permissions: read-all

jobs:
  dev-build:
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
    uses: ./.github/workflows/_build.yml
    with:
      projectName: stg-sdk-golang

  dev-release:
    needs: [ "dev-build" ]
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
    uses: ./.github/workflows/_release.yml
    with:
      major: 1
      minor: 1
      projectName: stg-sdk-golang
      contentType: sh

