name: feature_bug
on:
  push:
    branches:
      - "feature/**"
      - "bug/**"
      - "bugfix/**"

permissions: read-all

jobs:
  feature-bug-build:
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
    uses: ./.github/workflows/_build.yml
    with:
      projectName: stg-sdk-golang


